language: node_js
node_js:
  - 'stable'
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
sudo: required
script:
  - npm test
after_script:
  - npm run test-coverage
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
